### ISSUE TITLE
issue with the connection to the custom sparql-endpoint

### ISSUE THREAD

**Issue by maria-grigorieva** [ontodia-org/ontodia#30]
Hi, 
I have a problem with http://localhost:10444/sparql.html page. 
It doesn't connect to my SPARQL_ENDPOINT, which is set as environment variable. 

Return the following error:

Error: Must provide a proper URL as target
    at ProxyServer.<anonymous> (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/http-proxy/lib/http-proxy/index.js:68:35)
    at Server.<anonymous> (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/webpack-dev-server/lib/Server.js:147:14)
    at Layer.handle [as handle_request] (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/Maria/MegaPanDA/DKC/NodeJS/ontodia/node_modules/express/lib/router/route.js:131:14)

**Comment by yuricus** [comment]
Hi Maria! 
what OS are you using? and do you specify endpoint with http schema prefix?
on Linux/MacOS the following should work:
SPARQL_ENDPOINT=http://dbpedia.org/sparql npm run demo
endpoint URL should include http:// or https:// schema.

**Comment by maria-grigorieva** [comment]
I'm using Mac OS. 
I tried SPARQL_ENDPOINT=http://dbpedia.org/sparql npm run demo
Now there is no errors in npm console, but the page http://localhost:10444/sparql.html doesn't response. JavaScript console returns error POST http://localhost:10444/sparql-endpoint 409 (Invalid path)

**Comment by yuricus** [comment]
It was my mistake recommending dbpedia public endpoint since only experimental branch of Ontodia supports that. Current stable version of Ontodia supports only SPARQL endpoints with support of POST version of SPARQL 1.1 protocol, that's not the case with Virtuozo and dbpedia.org.

It took some time to find working sparql endpoint that works with ontodia. This works for me from master branch:

SPARQL_ENDPOINT=http://iswc2015.apps.vismart.biz/sparql npm run demo

For dbpedia to work in Ontodia master branch we'll have to wait for serveral days to confirm everything's working as expected.

**Comment by maria-grigorieva** [comment]
Thank you ) But my real plan was to try Ontodia with Virtuoso SPARQL endpoint )) 
Your visual interface really fits my project needs... I tried http://app.ontodia.org/ (with Virtuoso SPARQL Endpoint) - it works, in general.

**Comment by maria-grigorieva** [comment]
So, which non-stable version will be better to use with Virtuoso Endpoint?

**Comment by yuricus** [comment]
app.ontodia.org uses another data access pipeline with Java-based Sparql client. 
To try Ontodia with Virtuoso endpoint I recommend checking out sparql-provider-refactor branch, set SPARQL_ENDPOINT to Virtuoso and try /sparql.html
initialization code is at src/examples/sparql.ts:30

```
    const layoutData = tryLoadLayoutFromLocalStorage();
    model.importLayout({
        layoutData,
        validateLinks: true,
        dataProvider: new SparqlDataProvider({
            endpointUrl: '/sparql-endpoint',
            imagePropertyUris: [
                'http://collection.britishmuseum.org/id/ontology/PX_has_main_representation',
                'http://xmlns.com/foaf/0.1/img',
            ],
            queryMethod: SparqlQueryMethod.GET
        }, OWLStatsSettings),
    });
```
SparqlQueryMethod.GET is supported by Virtuozo.

**Comment by maria-grigorieva** [comment]
Yep! ) It's OK now! Thank you very much!
